In [26]:
import json
import pandas as pd

with open("../data/train/outcomes.json", "r", encoding="utf-8") as f:
    data = json.load(f)

data.keys()

dict_keys(['challenge_id', 'episodes', 'schema_version', 'split'])

In [27]:
rows = []

for episode in data["episodes"]:
    rows.append({
        "episode_id": episode["episode_id"],
        "ax31": float(episode["models"]["ax31"]["score"]),
        "ax31_light": float(episode["models"]["ax31-light"]["score"]),
        "ax31_think": float(episode["models"]["axk1-think"]["score"])
    })

df = pd.DataFrame(rows)

df.head()

   episode_id  ax31  ax31_light  ax31_think
0  train-0001   0.5         0.0         1.0
1  train-0002   1.0         1.0         1.0
2  train-0003   0.0         0.0         0.0
3  train-0004   0.5         1.0         0.0
4  train-0005   1.0         1.0         1.0

In [28]:
df["light_gap"] = df["ax31"] - df["ax31_light"]

light_failure = df[df["light_gap"] > 0].copy()

light_failure = light_failure.sort_values(
    "light_gap",
    ascending=False
)

light_failure.head(20)

      episode_id  ax31  ax31_light  ax31_think  light_gap
879   train-0880   1.0         0.0         0.5        1.0
777   train-0778   1.0         0.0         1.0        1.0
659   train-0660   1.0         0.0         1.0        1.0
666   train-0667   1.0         0.0         1.0        1.0
667   train-0668   1.0         0.0         1.0        1.0
1371  train-1372   1.0         0.0         1.0        1.0
1367  train-1368   1.0         0.0         1.0        1.0
1365  train-1366   1.0         0.0         1.0        1.0
687   train-0688   1.0         0.0         1.0        1.0
695   train-0696   1.0         0.0         1.0        1.0
1347  train-1348   1.0         0.0         1.0        1.0
1345  train-1346   1.0         0.0         1.0        1.0
1344  train-1345   1.0         0.0         1.0        1.0
709   train-0710   1.0         0.0         1.0        1.0
719   train-0720   1.0         0.0         1.0        1.0
1343  train-1344   1.0         0.0         1.0        1.0
1339  train-1340   1.0         0.0         1.0        1.0
1338  train-1339   1.0         0.0         1.0        1.0
767   train-0768   1.0         0.0         0.0        1.0
655   train-0656   1.0         0.0         0.0        1.0

In [29]:
strong_failure = df[
    (df["ax31"] > df["ax31_light"]) &
    (df["ax31"] == 1)
].copy()

strong_failure = strong_failure.sort_values(
    "light_gap",
    ascending=False
)

strong_failure.head(30)

      episode_id  ax31  ax31_light  ax31_think  light_gap
15    train-0016   1.0         0.0         0.0        1.0
992   train-0993   1.0         0.0         1.0        1.0
1038  train-1039   1.0         0.0         1.0        1.0
1067  train-1068   1.0         0.0         1.0        1.0
1077  train-1078   1.0         0.0         1.0        1.0
1103  train-1104   1.0         0.0         1.0        1.0
1108  train-1109   1.0         0.0         1.0        1.0
1111  train-1112   1.0         0.0         1.0        1.0
1123  train-1124   1.0         0.0         1.0        1.0
1161  train-1162   1.0         0.0         1.0        1.0
1185  train-1186   1.0         0.0         1.0        1.0
1195  train-1196   1.0         0.0         1.0        1.0
1205  train-1206   1.0         0.0         1.0        1.0
1213  train-1214   1.0         0.0         1.0        1.0
1227  train-1228   1.0         0.0         1.0        1.0
1229  train-1230   1.0         0.0         1.0        1.0
1241  train-1242   1.0         0.0         1.0        1.0
1250  train-1251   1.0         0.0         1.0        1.0
1255  train-1256   1.0         0.0         1.0        1.0
999   train-1000   1.0         0.0         1.0        1.0
949   train-0950   1.0         0.0         1.0        1.0
1286  train-1287   1.0         0.0         1.0        1.0
947   train-0948   1.0         0.0         0.5        1.0
709   train-0710   1.0         0.0         1.0        1.0
719   train-0720   1.0         0.0         1.0        1.0
767   train-0768   1.0         0.0         0.0        1.0
768   train-0769   1.0         0.0         1.0        1.0
777   train-0778   1.0         0.0         1.0        1.0
800   train-0801   1.0         0.0         1.0        1.0
849   train-0850   1.0         0.0         0.5        1.0

In [30]:
import json
import pandas as pd

# 1. inputs-base.json 불러오기
with open("../data/train/inputs-base.json", "r", encoding="utf-8") as f:
    raw_data = json.load(f)

# 2. episodes만 DataFrame으로 변환
prompt_df = pd.DataFrame(raw_data["episodes"])

# 3. 확인
print(prompt_df.columns)
print(prompt_df.head())

Index(['episode_id', 'prompt'], dtype='object')
   episode_id                                             prompt
0  train-0001  Round -63865955 to the nearest one hundred tho...
1  train-0002  def f(text):\n    if text and text.isupper():\...
2  train-0003  무인 달 궤도탐사선인 찬드라야안-1은 달표면을 초당 1.5km(시간당 3000마일)...
3  train-0004  Question: What happens if you cry during the N...
4  train-0005  def f(text):\n    return text.count('-') == le...

In [31]:
result_sorted = result.sort_values(
    "light_gap",
    ascending=False
)

result_sorted[[
    "episode_id",
    "ax31",
    "ax31_light",
    "ax31_think",
    "light_gap",
    "prompt"
]].head(30)

NameError: name 'result' is not defined

In [32]:
pd.set_option("display.max_colwidth", None)

for i in range(10):
    row = result_sorted.iloc[i]

    print("=" * 80)
    print(f"{i+1}. {row['episode_id']}")
    print(f"ax31={row['ax31']} | light={row['ax31_light']} | think={row['ax31_think']} | gap={row['light_gap']}")
    print("-" * 80)
    print(row["prompt"])
    print()

NameError: name 'result_sorted' is not defined

In [33]:
with open("../data/train/light_failure_cases.txt", "w", encoding="utf-8") as f:
    for _, row in result_sorted.head(30).iterrows():
        f.write("=" * 100 + "\n")
        f.write(f"Episode: {row['episode_id']}\n")
        f.write(f"ax31: {row['ax31']}\n")
        f.write(f"ax31-light: {row['ax31_light']}\n")
        f.write(f"ax31-think: {row['ax31_think']}\n")
        f.write(f"light_gap: {row['light_gap']}\n")
        f.write("-" * 100 + "\n")
        f.write(str(row["prompt"]))
        f.write("\n\n")

NameError: name 'result_sorted' is not defined

In [34]:
print(strong_failure.columns)
print(strong_failure.head())

Index(['episode_id', 'ax31', 'ax31_light', 'ax31_think', 'light_gap'], dtype='object')
      episode_id  ax31  ax31_light  ax31_think  light_gap
15    train-0016   1.0         0.0         0.0        1.0
992   train-0993   1.0         0.0         1.0        1.0
1038  train-1039   1.0         0.0         1.0        1.0
1067  train-1068   1.0         0.0         1.0        1.0
1077  train-1078   1.0         0.0         1.0        1.0

In [35]:
import json
import pandas as pd

with open("../data/train/inputs-base.json", "r", encoding="utf-8") as f:
    raw_data = json.load(f)

prompt_df = pd.DataFrame(raw_data["episodes"])

print(prompt_df.columns)
print(prompt_df.head())

Index(['episode_id', 'prompt'], dtype='object')
   episode_id  \
0  train-0001
1  train-0002
2  train-0003
3  train-0004
4  train-0005

                                                                                                                                                                                                                                                                                      prompt
0                                                                                                                                                                                                                                       Round -63865955 to the nearest one hundred thousand.
1                                           def f(text):\n    if text and text.isupper():\n        cs = str.maketrans(string.ascii_uppercase, string.ascii_lowercase)\n        return text.translate(cs)\n    return text.lower()[:3]\n\nassert f('mTYWLMwbLRVOqNEf.oLsYkZORKE[Ko[{n') == ??
2  무인 달 궤도탐사선인 찬드라야안-1은 달표면을 초당 1.5km(시간당 3000마일)의 속도로 날아가는 달 충돌형 탐사선(MIP)를 발사해 달의 남극 지방에 성공적으로 충돌하였다. 달 탐사선은 세 개의 중요한 과학 장비만 실려 있는 게 아니라, 사방에 인도 국기의 이미지가 그려져 있었습니다.\n\nQuestion: 다음 중 달 탐사선에 대한 설명으로 옳은 것은 무엇입니까?\nA. 달의 북극 지방에 착륙했다\nB. 불시착에 성공했다\nC. 유인 궤도선에서 발사됐다\nD. 2개의 필수 장비를 싣고 있었다
3                                                                                                        Question: What happens if you cry during the New Year?\nA. If you cry during the New Year, you will cry for the rest of the year\nB. Nothing happens if you cry during the New Year
4                                                                                                                                                                                                        def f(text):\n    return text.count('-') == len(text)\n\nassert f("---123-4") == ??

In [36]:
result = strong_failure.merge(
    prompt_df,
    on="episode_id",
    how="left"
)

print(result.columns)
print(len(result))

Index(['episode_id', 'ax31', 'ax31_light', 'ax31_think', 'light_gap',
       'prompt'],
      dtype='object')
240

In [37]:
def analyze_prompt(text):
    text = "" if pd.isna(text) else str(text)

    return {
        "length": len(text),
        "word_count": len(text.split()),
        "line_count": text.count("\n") + 1,

        "has_def": bool(re.search(r"\bdef\b", text)),
        "has_return": bool(re.search(r"\breturn\b", text)),
        "has_assert": bool(re.search(r"\bassert\b", text)),
        "has_if": bool(re.search(r"\bif\b", text)),
        "has_for": bool(re.search(r"\bfor\b", text)),
        "has_while": bool(re.search(r"\bwhile\b", text)),

        "has_calculate": bool(re.search(r"\bcalculate\b", text, re.I)),
        "has_probability": bool(
            re.search(r"\b(probability|prob of)\b", text, re.I)
        ),

        "has_question": "Question:" in text,
        "has_question_mark": "?" in text,

        "has_choices": bool(
            re.search(r"\b[A-D][.)]\s", text)
        ),
    }

In [38]:
feature_df = pd.DataFrame(
    result["prompt"].apply(analyze_prompt).tolist()
)

analysis_df = pd.concat(
    [
        result.reset_index(drop=True),
        feature_df.reset_index(drop=True)
    ],
    axis=1
)

NameError: name 're' is not defined

In [39]:
print(analysis_df.columns.tolist())

NameError: name 'analysis_df' is not defined

In [40]:
analysis_df.head()

NameError: name 'analysis_df' is not defined

In [41]:
analysis_df["light_failure"] = (
    analysis_df["light_gap"] > 0
).astype(int)

NameError: name 'analysis_df' is not defined

In [42]:
analysis_df["light_failure"].value_counts()

NameError: name 'analysis_df' is not defined

In [43]:
strong_failure = train_outcomes[
    train_outcomes["ax31"] > train_outcomes["ax31_light"]
]

NameError: name 'train_outcomes' is not defined

In [44]:
full_result = train_outcomes.merge(
    prompt_df,
    on="episode_id",
    how="left"
)
full_result["light_failure"] = (
    full_result["ax31"] > full_result["ax31_light"]
).astype(int)
print(full_result["light_failure"].value_counts())

NameError: name 'train_outcomes' is not defined

In [45]:
print(analysis_df["light_failure"].value_counts())

NameError: name 'analysis_df' is not defined

In [46]:
import json
import pandas as pd

with open("../data/train/outcomes.json", "r", encoding="utf-8") as f:
    outcomes_data = json.load(f)

print(type(outcomes_data))

<class 'dict'>

In [47]:
print(type(outcomes_data["episodes"]))
print(outcomes_data["episodes"][:2])

<class 'list'>
[{'episode_id': 'train-0001', 'models': {'ax31': {'input_tokens': 110, 'num_generations': 2, 'output_tokens': 229, 'score': '0.5'}, 'ax31-light': {'input_tokens': 112, 'num_generations': 2, 'output_tokens': 18, 'score': '0'}, 'axk1-think': {'input_tokens': 122, 'num_generations': 2, 'output_tokens': 4747, 'score': '1'}}}, {'episode_id': 'train-0002', 'models': {'ax31': {'input_tokens': 610, 'num_generations': 2, 'output_tokens': 80, 'score': '1'}, 'ax31-light': {'input_tokens': 646, 'num_generations': 2, 'output_tokens': 68, 'score': '1'}, 'axk1-think': {'input_tokens': 520, 'num_generations': 2, 'output_tokens': 4883, 'score': '1'}}}]

In [48]:
print(outcomes.keys())

NameError: name 'outcomes' is not defined

In [49]:
rows = []

for item in outcomes["episodes"]:
    rows.append({
        "episode_id": item["episode_id"],
        "ax31": float(item["models"]["ax31"]["score"]),
        "ax31_light": float(item["models"]["ax31-light"]["score"]),
        "ax31_think": float(item["models"]["axk1-think"]["score"])
    })

outcomes_df = pd.DataFrame(rows)

print(outcomes_df.head())

NameError: name 'outcomes' is not defined

In [50]:
outcomes_df["light_failure"] = (
    outcomes_df["ax31"] > outcomes_df["ax31_light"]
).astype(int)

print(outcomes_df["light_failure"].value_counts())

NameError: name 'outcomes_df' is not defined

In [51]:
print(
    outcomes_df[outcomes_df["light_failure"] == 1].head(20)
)

NameError: name 'outcomes_df' is not defined

In [52]:
full_result = outcomes_df.merge(
    prompt_df,
    on="episode_id",
    how="left"
)

NameError: name 'outcomes_df' is not defined

In [53]:
print(full_result.columns)
print(full_result.head())

NameError: name 'full_result' is not defined

In [54]:
failure_df = full_result[
    full_result["light_failure"] == 1
].copy()

NameError: name 'full_result' is not defined

In [55]:
failure_df[
    [
        "episode_id",
        "ax31",
        "ax31_light",
        "ax31_think",
        "prompt"
    ]
].head(20)

NameError: name 'failure_df' is not defined

In [56]:
full_result = outcomes_df.merge(
    prompt_df,
    on="episode_id",
    how="left"
)

print(full_result.columns)

NameError: name 'outcomes_df' is not defined

In [57]:
failure_df = full_result[
    full_result["light_failure"] == 1
].copy()

print("전체 train:", len(full_result))
print("light failure:", len(failure_df))

NameError: name 'full_result' is not defined

In [58]:
failure_df[
    ["episode_id", "ax31", "ax31_light", "ax31_think", "prompt"]
].head(10)

NameError: name 'failure_df' is not defined

In [59]:
feature_df = pd.DataFrame(
    full_result["prompt"].apply(analyze_prompt).tolist()
)

full_analysis = pd.concat(
    [
        full_result.reset_index(drop=True),
        feature_df.reset_index(drop=True)
    ],
    axis=1
)

NameError: name 'full_result' is not defined

In [60]:
print(full_analysis.shape)
print(full_analysis.columns.tolist())

NameError: name 'full_analysis' is not defined

In [9]:
python_features = [
    "has_def",
    "has_return",
    "has_assert",
    "has_if",
    "has_for",
    "has_while"
]

python_analysis = (
    full_analysis
    .groupby("light_failure")[python_features]
    .mean()
    .T
)

python_analysis.columns = [
    "light_success",
    "light_failure"
]

python_analysis["difference"] = (
    python_analysis["light_failure"]
    - python_analysis["light_success"]
)

python_analysis.sort_values(
    "difference",
    ascending=False
)

NameError: name 'full_analysis' is not defined

In [10]:
full_analysis["control_flow_count"] = (
    full_analysis["has_for"].astype(int)
    + full_analysis["has_if"].astype(int)
    + full_analysis["has_while"].astype(int)
)

control_failure = (
    full_analysis
    .groupby("control_flow_count")["light_failure"]
    .agg(["count", "mean"])
)

control_failure

NameError: name 'full_analysis' is not defined

In [11]:
control_combo = (
    full_analysis
    .groupby(
        ["has_for", "has_if", "has_while"]
    )["light_failure"]
    .agg(["count", "mean"])
    .sort_values("mean", ascending=False)
)

control_combo

NameError: name 'full_analysis' is not defined

In [12]:
math_features = [
    "has_calculate",
    "has_probability"
]

math_analysis = (
    full_analysis
    .groupby("light_failure")[math_features]
    .mean()
    .T
)

math_analysis.columns = [
    "light_success",
    "light_failure"
]

math_analysis["difference"] = (
    math_analysis["light_failure"]
    - math_analysis["light_success"]
)

math_analysis.sort_values(
    "difference",
    ascending=False
)

NameError: name 'full_analysis' is not defined

In [13]:
def analyze_prompt(text):
    text = "" if pd.isna(text) else str(text)

    return {
        "length": len(text),
        "word_count": len(text.split()),
        "line_count": text.count("\n") + 1,

        "has_def": bool(re.search(r"\bdef\b", text)),
        "has_return": bool(re.search(r"\breturn\b", text)),
        "has_assert": bool(re.search(r"\bassert\b", text)),
        "has_if": bool(re.search(r"\bif\b", text)),
        "has_for": bool(re.search(r"\bfor\b", text)),
        "has_while": bool(re.search(r"\bwhile\b", text)),

        "has_calculate": bool(
            re.search(r"\bcalculate\b", text, re.I)
        ),
        "has_probability": bool(
            re.search(r"\b(probability|prob of)\b", text, re.I)
        ),

        "has_question": "Question:" in text,
        "has_question_mark": "?" in text,

        "has_choices": bool(
            re.search(r"\b[A-D][.)]\s", text)
        ),

        # reasoning 후보
        "has_what_is": bool(
            re.search(r"\bwhat is\b", text, re.I)
        ),
        "has_what_if": bool(
            re.search(r"\bwhat happens if\b", text, re.I)
        ),
        "has_determine": bool(
            re.search(r"\bdetermine\b", text, re.I)
        ),
        "has_explain": bool(
            re.search(r"\bexplain\b", text, re.I)
        ),
    }

In [14]:
feature_df = pd.DataFrame(
    full_result["prompt"].apply(analyze_prompt).tolist()
)

full_analysis = pd.concat(
    [
        full_result.reset_index(drop=True),
        feature_df.reset_index(drop=True)
    ],
    axis=1
)

NameError: name 'full_result' is not defined

In [61]:
# 다시

In [63]:
import pandas as pd
import numpy as np
import re
import json

with open("../data/train/outcomes.json", "r", encoding="utf-8") as f:
    outcomes_data = json.load(f)

print(type(outcomes_data))

<class 'dict'>

In [65]:
print(outcomes_data.keys())
print(type(outcomes_data["episodes"]))
print(len(outcomes_data["episodes"]))

dict_keys(['challenge_id', 'episodes', 'schema_version', 'split'])
<class 'list'>
1760

In [66]:
outcomes_df = pd.DataFrame([
    {
        "episode_id": item["episode_id"],
        "ax31": float(item["models"]["ax31"]["score"]),
        "ax31_light": float(item["models"]["ax31-light"]["score"]),
        "ax31_think": float(item["models"]["axk1-think"]["score"])
    }
    for item in outcomes_data["episodes"]
])

print(outcomes_df.head())
print(outcomes_df.shape)

   episode_id  ax31  ax31_light  ax31_think
0  train-0001   0.5         0.0         1.0
1  train-0002   1.0         1.0         1.0
2  train-0003   0.0         0.0         0.0
3  train-0004   0.5         1.0         0.0
4  train-0005   1.0         1.0         1.0
(1760, 4)

In [67]:
outcomes_df["light_failure"] = (
    outcomes_df["ax31"] > outcomes_df["ax31_light"]
).astype(int)

print(
    outcomes_df[
        ["episode_id", "ax31", "ax31_light", "ax31_think", "light_failure"]
    ].head(20)
)

    episode_id  ax31  ax31_light  ax31_think  light_failure
0   train-0001   0.5         0.0         1.0              1
1   train-0002   1.0         1.0         1.0              0
2   train-0003   0.0         0.0         0.0              0
3   train-0004   0.5         1.0         0.0              0
4   train-0005   1.0         1.0         1.0              0
5   train-0006   0.0         0.0         0.0              0
6   train-0007   1.0         1.0         1.0              0
7   train-0008   1.0         1.0         1.0              0
8   train-0009   0.0         0.5         0.0              0
9   train-0010   0.0         0.0         0.0              0
10  train-0011   1.0         1.0         1.0              0
11  train-0012   1.0         1.0         1.0              0
12  train-0013   1.0         1.0         1.0              0
13  train-0014   1.0         1.0         1.0              0
14  train-0015   1.0         1.0         1.0              0
15  train-0016   1.0         0.0         0.0              1
16  train-0017   1.0         0.5         1.0              1
17  train-0018   0.0         0.0         0.5              0
18  train-0019   1.0         1.0         1.0              0
19  train-0020   1.0         1.0         1.0              0

In [68]:
prompt_raw = pd.read_json(
    "../data/train/inputs-base.json"
)

print(prompt_raw.columns)
print(prompt_raw.head())

Index(['challenge_id', 'episodes', 'schema_version', 'split'], dtype='object')
                     challenge_id  \
0  ossp-2026-llm-router-challenge
1  ossp-2026-llm-router-challenge
2  ossp-2026-llm-router-challenge
3  ossp-2026-llm-router-challenge
4  ossp-2026-llm-router-challenge

                                                                                                                                                                                                                                                                                                                        episodes  \
0                                                                                                                                                                                                                                 {'episode_id': 'train-0001', 'prompt': 'Round -63865955 to the nearest one hundred thousand.'}
1                                           {'episode_id': 'train-0002', 'prompt': 'def f(text):
    if text and text.isupper():
        cs = str.maketrans(string.ascii_uppercase, string.ascii_lowercase)
        return text.translate(cs)
    return text.lower()[:3]

assert f('mTYWLMwbLRVOqNEf.oLsYkZORKE[Ko[{n') == ??'}
2  {'episode_id': 'train-0003', 'prompt': '무인 달 궤도탐사선인 찬드라야안-1은 달표면을 초당 1.5km(시간당 3000마일)의 속도로 날아가는 달 충돌형 탐사선(MIP)를 발사해 달의 남극 지방에 성공적으로 충돌하였다. 달 탐사선은 세 개의 중요한 과학 장비만 실려 있는 게 아니라, 사방에 인도 국기의 이미지가 그려져 있었습니다.

Question: 다음 중 달 탐사선에 대한 설명으로 옳은 것은 무엇입니까?
A. 달의 북극 지방에 착륙했다
B. 불시착에 성공했다
C. 유인 궤도선에서 발사됐다
D. 2개의 필수 장비를 싣고 있었다'}
3                                                                                                    {'episode_id': 'train-0004', 'prompt': 'Question: What happens if you cry during the New Year?
A. If you cry during the New Year, you will cry for the rest of the year
B. Nothing happens if you cry during the New Year'}
4                                                                                                                                                                                                     {'episode_id': 'train-0005', 'prompt': 'def f(text):
    return text.count('-') == len(text)

assert f("---123-4") == ??'}

   schema_version  split
0               1  train
1               1  train
2               1  train
3               1  train
4               1  train

In [69]:
prompt_df = pd.json_normalize(
    prompt_raw["episodes"]
)

print(prompt_df.columns)
print(prompt_df.head())

Index(['episode_id', 'prompt'], dtype='object')
   episode_id  \
0  train-0001
1  train-0002
2  train-0003
3  train-0004
4  train-0005

                                                                                                                                                                                                                                                                                      prompt
0                                                                                                                                                                                                                                       Round -63865955 to the nearest one hundred thousand.
1                                           def f(text):\n    if text and text.isupper():\n        cs = str.maketrans(string.ascii_uppercase, string.ascii_lowercase)\n        return text.translate(cs)\n    return text.lower()[:3]\n\nassert f('mTYWLMwbLRVOqNEf.oLsYkZORKE[Ko[{n') == ??
2  무인 달 궤도탐사선인 찬드라야안-1은 달표면을 초당 1.5km(시간당 3000마일)의 속도로 날아가는 달 충돌형 탐사선(MIP)를 발사해 달의 남극 지방에 성공적으로 충돌하였다. 달 탐사선은 세 개의 중요한 과학 장비만 실려 있는 게 아니라, 사방에 인도 국기의 이미지가 그려져 있었습니다.\n\nQuestion: 다음 중 달 탐사선에 대한 설명으로 옳은 것은 무엇입니까?\nA. 달의 북극 지방에 착륙했다\nB. 불시착에 성공했다\nC. 유인 궤도선에서 발사됐다\nD. 2개의 필수 장비를 싣고 있었다
3                                                                                                        Question: What happens if you cry during the New Year?\nA. If you cry during the New Year, you will cry for the rest of the year\nB. Nothing happens if you cry during the New Year
4                                                                                                                                                                                                        def f(text):\n    return text.count('-') == len(text)\n\nassert f("---123-4") == ??

In [70]:
full_result = outcomes_df.merge(
    prompt_df[["episode_id", "prompt"]],
    on="episode_id",
    how="left"
)

print(full_result.columns)
print(full_result.shape)

Index(['episode_id', 'ax31', 'ax31_light', 'ax31_think', 'light_failure',
       'prompt'],
      dtype='object')
(1760, 6)

In [71]:
print(full_result[
    ["episode_id", "light_failure", "prompt"]
].head(10).to_string())

   episode_id  light_failure                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    

In [72]:
def analyze_prompt(text):
    text = "" if pd.isna(text) else str(text)

    return {
        "length": len(text),
        "word_count": len(text.split()),
        "line_count": text.count("\n") + 1,

        "has_def": bool(
            re.search(r"\bdef\b", text)
        ),
        "has_return": bool(
            re.search(r"\breturn\b", text)
        ),
        "has_assert": bool(
            re.search(r"\bassert\b", text)
        ),
        "has_if": bool(
            re.search(r"\bif\b", text)
        ),
        "has_for": bool(
            re.search(r"\bfor\b", text)
        ),
        "has_while": bool(
            re.search(r"\bwhile\b", text)
        ),

        "has_calculate": bool(
            re.search(r"\bcalculate\b", text, re.I)
        ),
        "has_probability": bool(
            re.search(r"\b(probability|prob of)\b", text, re.I)
        ),

        "has_question": "Question:" in text,
        "has_question_mark": "?" in text,

        "has_choices": bool(
            re.search(r"\b[A-D][.)]\s", text)
        )
    }

In [73]:
feature_df = pd.DataFrame(
    full_result["prompt"].apply(analyze_prompt).tolist()
)

print(feature_df.head())
print(feature_df.columns)

   length  word_count  line_count  has_def  has_return  has_assert  has_if  \
0      52           8           1    False       False       False   False
1     234          18           7     True        True        True    True
2     275          64           7    False       False       False   False
3     177          37           3    False       False       False    True
4      80          10           4     True        True        True   False

   has_for  has_while  has_calculate  has_probability  has_question  \
0    False      False          False            False         False
1    False      False          False            False         False
2    False      False          False            False          True
3     True      False          False            False          True
4    False      False          False            False         False

   has_question_mark  has_choices
0              False        False
1               True        False
2               True         True
3               True         True
4               True        False
Index(['length', 'word_count', 'line_count', 'has_def', 'has_return',
       'has_assert', 'has_if', 'has_for', 'has_while', 'has_calculate',
       'has_probability', 'has_question', 'has_question_mark', 'has_choices'],
      dtype='object')

In [74]:
full_analysis = pd.concat(
    [
        full_result.reset_index(drop=True),
        feature_df.reset_index(drop=True)
    ],
    axis=1
)

print(full_analysis.shape)
print(full_analysis.columns)

(1760, 20)
Index(['episode_id', 'ax31', 'ax31_light', 'ax31_think', 'light_failure',
       'prompt', 'length', 'word_count', 'line_count', 'has_def', 'has_return',
       'has_assert', 'has_if', 'has_for', 'has_while', 'has_calculate',
       'has_probability', 'has_question', 'has_question_mark', 'has_choices'],
      dtype='object')

In [75]:
print(
    full_analysis["light_failure"]
    .value_counts()
)

light_failure
0    1438
1     322
Name: count, dtype: int64

In [76]:
print(
    full_analysis["light_failure"].mean()
)

0.18295454545454545

In [78]:
# python feature 분석

In [79]:
python_features = [
    "has_for",
    "has_if",
    "has_while",
    "has_return",
    "has_def",
    "has_assert"
]

python_analysis = (
    full_analysis
    .groupby("light_failure")[python_features]
    .mean()
    .T
)

python_analysis.columns = [
    "light_success",
    "light_failure"
]

python_analysis["difference"] = (
    python_analysis["light_failure"]
    - python_analysis["light_success"]
)

python_analysis.sort_values(
    "difference",
    ascending=False
)

            light_success  light_failure  difference
has_for          0.210014       0.248447    0.038433
has_if           0.166898       0.195652    0.028754
has_while        0.098748       0.127329    0.028581
has_return       0.190542       0.192547    0.002004
has_def          0.141168       0.118012   -0.023156
has_assert       0.148818       0.121118   -0.027700

In [80]:
full_analysis["control_flow_count"] = (
    full_analysis["has_for"].astype(int)
    + full_analysis["has_if"].astype(int)
    + full_analysis["has_while"].astype(int)
)

In [81]:
control_analysis = (
    full_analysis
    .groupby("control_flow_count")["light_failure"]
    .agg(["count", "mean"])
)

control_analysis

                    count      mean
control_flow_count
0                    1279  0.179046
1                     232  0.150862
2                     111  0.225225
3                     138  0.239130

In [82]:
# reasoning, 문답형 분석

In [83]:
reasoning_features = [
    "has_question",
    "has_question_mark",
    "has_choices"
]

reasoning_analysis = (
    full_analysis
    .groupby("light_failure")[reasoning_features]
    .mean()
    .T
)

reasoning_analysis.columns = [
    "light_success",
    "light_failure"
]

reasoning_analysis["difference"] = (
    reasoning_analysis["light_failure"]
    - reasoning_analysis["light_success"]
)

reasoning_analysis.sort_values(
    "difference",
    ascending=False
)

                   light_success  light_failure  difference
has_choices             0.321280       0.310559   -0.010721
has_question            0.440890       0.422360   -0.018530
has_question_mark       0.746175       0.683230   -0.062945

In [84]:
# prompt 길이 영향 확인

In [85]:
length_analysis = (
    full_analysis
    .groupby("light_failure")[
        ["length", "word_count", "line_count"]
    ]
    .mean()
)

length_analysis.index = [
    "light_success",
    "light_failure"
]

length_analysis

                    length   word_count  line_count
light_success  3840.913074   675.346314   53.369263
light_failure  5981.875776  1045.263975   82.397516

In [86]:
# prompt 길이 구간으로 나누기

In [87]:
full_analysis["length_bin"] = pd.cut(
    full_analysis["length"],
    bins=[0, 1000, 2000, 3000, 5000, 7000, 10000, np.inf],
    labels=[
        "0-1k",
        "1-2k",
        "2-3k",
        "3-5k",
        "5-7k",
        "7-10k",
        "10k+"
    ]
)

length_bin_analysis = (
    full_analysis
    .groupby("length_bin", observed=False)["light_failure"]
    .agg(["count", "mean"])
)

length_bin_analysis

            count      mean
length_bin
0-1k         1569  0.174634
1-2k            7  0.142857
2-3k            0       NaN
3-5k            0       NaN
5-7k            0       NaN
7-10k           0       NaN
10k+          160  0.243750

In [88]:
# 10k 이상에서 실제로 얼마나 실패하는가

In [89]:
long_prompt_analysis = (
    full_analysis
    .assign(
        is_very_long=full_analysis["length"] >= 10000
    )
    .groupby("is_very_long")["light_failure"]
    .agg(["count", "mean"])
)

long_prompt_analysis

              count      mean
is_very_long
False          1600  0.176875
True            160  0.243750

In [90]:
full_analysis["complex_control"] = (
    full_analysis["control_flow_count"] >= 2
)

full_analysis["very_long"] = (
    full_analysis["length"] >= 10000
)

interaction_analysis = (
    full_analysis
    .groupby(["very_long", "complex_control"])["light_failure"]
    .agg(["count", "mean"])
)

interaction_analysis

                           count      mean
very_long complex_control
False     False             1509  0.174950
          True                91  0.208791
True      False                2  0.000000
          True               158  0.246835